# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\027io.coded.seabird.commonZ\004.;pb',
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"#\n\x07\x42\x61\x63kend\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"(\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\":\n\x07\x43hannel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\"?\n\rChannelSource\x12\x12\n\nchannel_id\x18\x01 \x01(\t\x12\x1a\n\x04user\x18\x02 \x01(\x0b\x32\x0c.common.User\"C\n\x0cMessageEvent\x12%\n\x06source\x18\x01 \x01(\x0b\x32\x15.common.ChannelSource\x12\x0c\n\x04text\x18\x02 \x01(\t\"A\n\x13PrivateMessageEvent\x12\x1c\n\x06source\x18\x01 \x01(\x0b\x32\x0c.common.User\x12\x0c\n\x04text\x18\x02 \x01(\t\"C\n\x0cMentionEvent\x12%\n\x06source\x18\x01 \x01(\x0b\x32\x15.common.ChannelSource\x12\x0c\n\x04text\x18\x02 \x01(\t\"S\n\x0c\x43ommandEvent\x12%\n\x06source\x18\x01 \x01(\x0b\x32\x15.common.ChannelSource\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0b\n\x03\x61rg\x18\x03 \x01(\t\"B\n\x0b\x41\x63tionEvent\x12%\n\x06source\x18\x01 \x01(\x0b\x32\x15.common.ChannelSource\x12\x0c\n\x04text\x18\x02 \x01(\t\"@\n\x12PrivateActionEvent\x12\x1c\n\x06source\x18\x01 \x01(\x0b\x32\x0c.common.User\x12\x0c\n\x04text\x18\x02 \x01(\tB\x1f\n\x17io.coded.seabird.commonZ\x04.;pbb\x06proto3'
)




_BACKEND = _descriptor.Descriptor(
  name='Backend',
  full_name='common.Backend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.Backend.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='common.Backend.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=59,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='common.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='common.User.display_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=101,
)


_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='common.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.Channel.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='common.Channel.display_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='common.Channel.topic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=161,
)


_CHANNELSOURCE = _descriptor.Descriptor(
  name='ChannelSource',
  full_name='common.ChannelSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='common.ChannelSource.channel_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='common.ChannelSource.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=226,
)


_MESSAGEEVENT = _descriptor.Descriptor(
  name='MessageEvent',
  full_name='common.MessageEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='common.MessageEvent.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='common.MessageEvent.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=295,
)


_PRIVATEMESSAGEEVENT = _descriptor.Descriptor(
  name='PrivateMessageEvent',
  full_name='common.PrivateMessageEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='common.PrivateMessageEvent.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='common.PrivateMessageEvent.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=362,
)


_MENTIONEVENT = _descriptor.Descriptor(
  name='MentionEvent',
  full_name='common.MentionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='common.MentionEvent.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='common.MentionEvent.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=431,
)


_COMMANDEVENT = _descriptor.Descriptor(
  name='CommandEvent',
  full_name='common.CommandEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='common.CommandEvent.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='common.CommandEvent.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg', full_name='common.CommandEvent.arg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=516,
)


_ACTIONEVENT = _descriptor.Descriptor(
  name='ActionEvent',
  full_name='common.ActionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='common.ActionEvent.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='common.ActionEvent.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=518,
  serialized_end=584,
)


_PRIVATEACTIONEVENT = _descriptor.Descriptor(
  name='PrivateActionEvent',
  full_name='common.PrivateActionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='common.PrivateActionEvent.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='common.PrivateActionEvent.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=586,
  serialized_end=650,
)

_CHANNELSOURCE.fields_by_name['user'].message_type = _USER
_MESSAGEEVENT.fields_by_name['source'].message_type = _CHANNELSOURCE
_PRIVATEMESSAGEEVENT.fields_by_name['source'].message_type = _USER
_MENTIONEVENT.fields_by_name['source'].message_type = _CHANNELSOURCE
_COMMANDEVENT.fields_by_name['source'].message_type = _CHANNELSOURCE
_ACTIONEVENT.fields_by_name['source'].message_type = _CHANNELSOURCE
_PRIVATEACTIONEVENT.fields_by_name['source'].message_type = _USER
DESCRIPTOR.message_types_by_name['Backend'] = _BACKEND
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL
DESCRIPTOR.message_types_by_name['ChannelSource'] = _CHANNELSOURCE
DESCRIPTOR.message_types_by_name['MessageEvent'] = _MESSAGEEVENT
DESCRIPTOR.message_types_by_name['PrivateMessageEvent'] = _PRIVATEMESSAGEEVENT
DESCRIPTOR.message_types_by_name['MentionEvent'] = _MENTIONEVENT
DESCRIPTOR.message_types_by_name['CommandEvent'] = _COMMANDEVENT
DESCRIPTOR.message_types_by_name['ActionEvent'] = _ACTIONEVENT
DESCRIPTOR.message_types_by_name['PrivateActionEvent'] = _PRIVATEACTIONEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Backend = _reflection.GeneratedProtocolMessageType('Backend', (_message.Message,), {
  'DESCRIPTOR' : _BACKEND,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Backend)
  })
_sym_db.RegisterMessage(Backend)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.User)
  })
_sym_db.RegisterMessage(User)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Channel)
  })
_sym_db.RegisterMessage(Channel)

ChannelSource = _reflection.GeneratedProtocolMessageType('ChannelSource', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELSOURCE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.ChannelSource)
  })
_sym_db.RegisterMessage(ChannelSource)

MessageEvent = _reflection.GeneratedProtocolMessageType('MessageEvent', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEEVENT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.MessageEvent)
  })
_sym_db.RegisterMessage(MessageEvent)

PrivateMessageEvent = _reflection.GeneratedProtocolMessageType('PrivateMessageEvent', (_message.Message,), {
  'DESCRIPTOR' : _PRIVATEMESSAGEEVENT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.PrivateMessageEvent)
  })
_sym_db.RegisterMessage(PrivateMessageEvent)

MentionEvent = _reflection.GeneratedProtocolMessageType('MentionEvent', (_message.Message,), {
  'DESCRIPTOR' : _MENTIONEVENT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.MentionEvent)
  })
_sym_db.RegisterMessage(MentionEvent)

CommandEvent = _reflection.GeneratedProtocolMessageType('CommandEvent', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDEVENT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.CommandEvent)
  })
_sym_db.RegisterMessage(CommandEvent)

ActionEvent = _reflection.GeneratedProtocolMessageType('ActionEvent', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONEVENT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.ActionEvent)
  })
_sym_db.RegisterMessage(ActionEvent)

PrivateActionEvent = _reflection.GeneratedProtocolMessageType('PrivateActionEvent', (_message.Message,), {
  'DESCRIPTOR' : _PRIVATEACTIONEVENT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.PrivateActionEvent)
  })
_sym_db.RegisterMessage(PrivateActionEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
